### ISSUE TITLE
Parse error when calling Applications.getApplication

### ISSUE THREAD

**Issue by enrico-ghidoni** [allquixotic/encuum#18]
Hi there

I successfully managed to get encuum working prior to updating the local codebase to 770304824d39ee1eca1db56cdf0338db7ffba189. After pulling that commit I get

```
cargo run --release
    Finished release [optimized] target(s) in 0.10s
     Running `target/release/encuum`
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Parse error: invalid type: integer `0`, expected a string at line 1 column 60

Caused by:
    invalid type: integer `0`, expected a string at line 1 column 60', src/main.rs:195:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

on the very same `.env` configuration. Anything wrong on my side?

**Comment by allquixotic** [comment]
This looks like a type error with your data. Meaning, the Enjin API may have randomly changed (due to a server-side change), or your forum in particular is returning a pattern of data I haven't seen before.

I'm not sure how your .env is setup, but I don't see any detailed logs of encuum even starting its work. Normally I'd be able to see what kind of progress it was able to make before it started doing things.

Can you set `log_level=TRACE` in .env? And if you've set a `log_file` parameter, I need the contents of that log file. You may have to spend time redacting it to make sure I don't see your session key, etc.

**Comment by enrico-ghidoni** [comment]
Ran again and it did parse quite a lot of stuff before breaking, this is the .env

```
email=<REDACTED>
password=<REDACTED>
website=www.carpenoctem.co
database_file=cnto_exports_4/general_discussions_multimedia.sqlite
forum_ids=26081621
subforum_ids=5961709
log_level=TRACE
log_file=cnto_exports_4/general_discussions_multimedia.log
sanitize_log=true
```

And below is the last two responses before the error, the entire log file is quite long (18MB) so if this isn't enough info let me know I'll find a better way to send it

```
2023-03-30T18:44:20.682635Z TRACE method_call{method="Applications.getApplication"}: jsonrpsee_core::http_helpers: HTTP response body: {"result":{"application_id":"<REDACTED>","site_id":"821401","preset_id":0,"title":null,"user_ip":"<REDACTED>","is_mine":false,"can_manage":true,"created":"1426545227","updated":"1426545946","read":true,"comments":0,"app_comments":null,"admin_comments":null,"site_name":"Carpe Noctem - Tactical Operations","user_id":"<REDACTED>","is_online":false,"username":"<REDACTED>","avatar":"<REDACTED>","admin_user_id":"<REDACTED>","admin_online":false,"admin_username":"<REDACTED>","admin_avatar":"<REDACTED>","site_logo":"https:\/\/s3.amazonaws.com\/files.enjin.com\/821401\/site_logo\/medium.png","user_data":[],"is_archived":false,"is_trashed":false,"allow_app_comments":null,"post_app_comments":true,"allow_admin_comments":false},"id":"999","jsonrpc":"2.0"}
2023-03-30T18:44:20.682748Z TRACE method_call{method="Applications.getApplication"}: jsonrpsee_core::tracing: recv="{\"id\":\"<REDACTED>\",\"jsonrpc\":\"2.0\",\"result\":{\"admin_avatar\":\"<REDACTED>\",\"admin_comments\":null,\"admin_online\":false,\"admin_user_id\":\"<REDACTED>\",\"admin_username\":\"<REDACTED>\",\"allow_admin_comments\":false,\"allow_app_comments\":null,\"app_comments\":null,\"application_id\":\"<REDACTED>\",\"avatar\":\"<REDACTED>\",\"can_manage\":true,\"comments\":0,\"created\":\"1426545227\",\"is_archived\":false,\"is_mine\":false,\"is_online\":false,\"is_trashed\":false,\"post_app_comments\":true,\"preset_id\":0,\"read\":true,\"site_id\":\"821401\",\"site_logo\":\"https://s3.amazonaws.com/files.enjin.com/821401/site_logo/medium.png\",\"site_name\":\"Carpe Noctem - Tactical Operations\",\"title\":null,\"updated\":\"1426545946\",\"user_data\":[],\"user_id\":\"<REDACTED>\",\"user_ip\":\"<REDACTED>\",\"username\":\"<REDACTED>\"}}"
    thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Parse error: invalid type: integer `0`, expected a string at line 1 column 60
    
    Caused by:
        invalid type: integer `0`, expected a string at line 1 column 60', src/main.rs:195:38
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    2023-03-30T18:44:20.683225Z ERROR tokio_cron_scheduler::job::creator: Error running job 51c36e90-9b12-4562-b11f-256ce7cfb091 RecvError(())
    2023-03-30T18:44:20.683280Z TRACE want: signal: Want    
    2023-03-30T18:44:20.683294Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
    2023-03-30T18:44:21.205512Z TRACE hyper::client::pool: idle interval checking for expired
    2023-03-30T18:45:08.194833Z  INFO encuum: *** encuum memory usage: 68104192 bytes (68 MB)
```

**Comment by allquixotic** [comment]
Currently the code is tracking the `preset_id` in the response for `Applications.getApplication` as a String, but Enjin is passing it as an integer. I know how to fix this but need some time this weekend to work on it.

**Comment by enrico-ghidoni** [comment]
No worries, thank you for the help!

**Comment by enrico-ghidoni** [comment]
Running the tool again with the option `do_apps` set to `false` solves this problem. There is still an error that is unrelated to applications

```
thread 'tokio-runtime-worker' panicked at 'Thread: 31957741, Try #5: RPC call failed: ErrorObject { code: ServerError(-32099), message: "This operation encountered a fatal error, please contact support.", data: None }', src/forum.rs:200:25
```

I will re-run the export with detailed logs and keep you updated @allquixotic, let me know if you want a separate issue for this. I'm going to side with whoever suggests to send a PayPal for donations, your work is very much appreciated!

**Comment by allquixotic** [comment]
That message `This operation encountered a fatal error, please contact support.` indicates a server-side error in Enjin. Whatever post is failing to be retrieved probably can't be retrieved manually by visiting the forum either, because the website/forum viewing code just calls the same Enjin API as I'm calling, under the hood.

I've seen this happen when people post too many images and video links. Enjin is doing some kind of expensive content filtering on the backend with these, and when it takes too much time to do that, it just gives up and errors out.

Set `keep_going=true` in `.env` to bypass these types of failures. You won't be able to extract the forum posts from whichever page(s) fail with this error, but them's the breaks.

With `log_level=TRACE`, you should be able to figure out exactly which forum posts/pages are causing this behavior. Then you can visit the posts manually, and see if you can access it normally. If so, I'll investigate further to see what I can do from the encuum end. If not, you're outta luck.

**Comment by allquixotic** [comment]
Please make a new issue about the fatal error thing. This issue pertains to the code-up error in handling applications.

**Comment by allquixotic** [comment]
Added a donation link at the top of the readme. Thank you! I'll be continuing to work on encuum until enjin shuts down. I intend to fix this issue, but no promises about implementing some of the major missing pieces other than wiki. I HAVE to get wiki done because my own guild uses that.

**Comment by allquixotic** [comment]
The encuum project is now unmaintained. Another developer has managed to write a much more complete Enjin extractor over here: https://github.com/Kas-tle/EnjinScraper Please use that going forward.
